name: Alertas Discord

on:
  push:
    branches:
      - main

jobs:
  alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 Novo commit na branch main! Repositório: ${{ github.repository }} | Autor: ${{ github.actor }}\"}" \
          "$DISCORD_WEBHOOK"
